#%RAML 1.0 Trait

responses:
  408:
    body:
      application/json:
        type: CommonErrorType
        example: !include ../examples/error408-example.raml
    headers:
      source-system:
        description: specifies source system
        type:  string
        example: mfcs      
      correlation-id:
        description: specifies correlation between flows
        type:  string
        example: 1b611860-9aa1-458f-9789-0a30b0630c51
      target-system:
        description: specifies target system
        type:  string
        example: GCP