#%RAML 1.0 NamedExample
email-notice-example:
  noticeType: "EmailNotice"
  fromAddress: "admin@example.com"
  toAddress: "mail@example.com"
  emailSubject: "WARN:DEV:Event notification"
  emailBody: "Server memory consumption at 90% for the last 5 minutes"
