#%RAML 1.0 NamedExample
  success: false
  api_name: 'im-mfcs-api'
  version: '1.0.10'
  correlation_id: '2e623260-d394-11eb-9218-2698d9a14126'
  time_stamp: '2021-06-22T19:58:15.549Z'
  error_details: 
    -  
      code: 415
      reason: 'APIKIT:UNSUPPORTED_MEDIA_TYPE'
      message: 'Media Type not supported'
      
  
